import Head from "next/head"
import NavBar from "../components/navBar"


function Home() {
  return (
    <div className='container-fluid'>
      
      <Head>
        <title>FordaStore</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/main-logo.png' />
      </Head>

      <NavBar />
      
    </div>
  )
}

export default Home;