import Head from "next/head"
import NavBar from "../components/navBar"
import ListOfLink from "../components/listOfLink"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Forda Store</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/main-logo.png' />
      </Head>
      <NavBar/>
      <main>
        <ListOfLink/>
      </main>
    </div>
  )
}